/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

"use client"
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function MagicCat(props) {
  const { nodes, materials } = useGLTF('/models/anime_short_fluffy__1016015946_refine.glb')

  const modelRef = useRef();

  useFrame((state, delta, XRFrame) => {
    modelRef.current.position.y = 0.5 + Math.sin(state.clock.elapsedTime) * 0.2;
  })
  return (
    <group {...props} 
    dispose={null}
    ref={modelRef}
    scale={[2,2,2,2]}
    rotation={[0.25,0,0]}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_0.geometry}
        material={nodes.mesh_0.material}
      />
    </group>
  )
}

useGLTF.preload('/models/anime_short_fluffy__1016015946_refine.glb')